import React from "react";

const PrivacyPolicy = () => {
  return (
    <div className="container mx-auto px-6 py-10">
      {/* Main Heading */}
      <h1 className="text-2xl font-bold text-center mb-6">Privacy Policy</h1>
      <p className="text-right text-sm mb-4">Last updated: July 26, 2024</p>

      {/* Paragraph Section */}
      <p className="text-lg mb-4">
        This Privacy Policy describes Our policies and procedures on the
        collection, use, and disclosure of Your information when You use the
        Service and tells You about Your privacy rights and how the law protects
        You. We use Your Personal data to provide and improve the Service. By
        using the Service, You agree to the collection and use of information in
        accordance with this Privacy Policy.
      </p>

      {/* Subheading: Interpretation and Definitions */}
      <h2 className="text-xl font-semibold mb-4">
        Interpretation and Definitions
      </h2>

      {/* Subheading: Interpretation */}
      <h3 className="text-lg font-semibold mb-2">Interpretation</h3>
      <p className="text-lg mb-4">
        The words of which the initial letter is capitalized have meanings
        defined under the following conditions. The following definitions shall
        have the same meaning regardless of whether they appear in singular or
        in plural.
      </p>

      {/* Subheading: Definitions */}
      <h3 className="text-lg font-semibold mb-2">Definitions</h3>
      <p className="text-lg mb-4">For the purposes of this Privacy Policy:</p>

      {/* Bullet Points Section */}
      <ul className="list-disc pl-6 mb-4">
        <li>
          <strong>Account</strong> means a unique account created for You to
          access our Service or parts of our Service.
        </li>
        <li>
          <strong>Company</strong> (referred to as either "the Company", "We",
          "Us" or "Our" in this Agreement) refers to [Your Company Name].
        </li>
        <li>
          <strong>Cookies</strong> are small files that are placed on Your
          computer, mobile device or any other device by a website, containing
          the details of Your browsing history on that website among its many
          uses.
        </li>
        <li>
          <strong>Country</strong> refers to: Bangladesh.
        </li>
        <li>
          <strong>Device</strong> means any device that can access the Service
          such as a computer, a cellphone, or a digital tablet.
        </li>
        <li>
          <strong>Personal Data</strong> is any information that relates to an
          identified or identifiable individual.
        </li>
        <li>
          <strong>Service</strong> refers to the Website.
        </li>
        <li>
          <strong>Service Provider</strong> means any natural or legal person
          who processes the data on behalf of the Company. It refers to
          third-party companies or individuals employed by the Company to
          facilitate the Service, to provide the Service on behalf of the
          Company, to perform services related to the Service, or to assist the
          Company in analyzing how the Service is used.
        </li>
        <li>
          <strong>Usage Data</strong> refers to data collected automatically,
          either generated by the use of the Service or from the Service
          infrastructure itself (for example, the duration of a page visit).
        </li>
        <li>
          <strong>You</strong> means the individual accessing or using the
          Service, or the company, or other legal entity on behalf of which such
          individual is accessing or using the Service, as applicable.
        </li>
      </ul>

      {/* Subheading: Collecting and Using Your Personal Data */}
      <h2 className="text-xl font-semibold mb-4">
        Collecting and Using Your Personal Data
      </h2>

      {/* Subheading: Types of Data Collected */}
      <h3 className="text-lg font-semibold mb-2">Types of Data Collected</h3>

      {/* Subheading: Personal Data */}
      <h4 className="text-md font-semibold mb-2">Personal Data</h4>
      <p className="text-lg mb-4">
        While using Our Service, We may ask You to provide Us with certain
        personally identifiable information that can be used to contact or
        identify You. Personally identifiable information may include, but is
        not limited to:
      </p>

      {/* List of Personal Data */}
      <ul className="list-disc pl-6 mb-4">
        <li>Email address</li>
        <li>First name and last name</li>
        <li>Phone number</li>
        <li>Address, State, Province, ZIP/Postal code, City</li>
        <li>Usage Data</li>
      </ul>

      {/* Subheading: Usage Data */}
      <h4 className="text-md font-semibold mb-2">Usage Data</h4>
      <p className="text-lg mb-4">
        Usage Data is collected automatically when using the Service.
      </p>

      <p className="text-lg mb-4">
        Usage Data may include information such as Your Device's Internet
        Protocol address
      </p>
    </div>
  );
};
export default PrivacyPolicy;
